# Generated by Django 5.1.15 on 2026-05-26 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(blank=True, max_length=64)),
                ('clinical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='visits.visit')),
            ],
            options={
                'db_table': 'clinical_lab_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_summary', models.TextField()),
                ('result_file', models.FileField(blank=True, upload_to='lab_results/%Y/%m/')),
                ('is_abnormal', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='clinical.labrequest')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='visits.visit')),
            ],
            options={
                'db_table': 'clinical_lab_result',
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='visits.visit')),
            ],
            options={
                'db_table': 'clinical_prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=120)),
                ('duration', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.prescription')),
            ],
            options={
                'db_table': 'clinical_prescription_item',
            },
        ),
        migrations.CreateModel(
            name='TreatmentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('medication', 'Medication'), ('injection', 'Injection'), ('follow_up', 'Follow Up')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('medication_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_schedules', to='accounts.studentprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_schedules', to='visits.visit')),
            ],
            options={
                'db_table': 'clinical_treatment_schedule',
                'indexes': [models.Index(fields=['student', 'status'], name='clinical_tr_student_9d65a0_idx'), models.Index(fields=['visit', 'schedule_type'], name='clinical_tr_visit_i_57d44a_idx')],
            },
        ),
    ]
