# Generated by Django 5.1.15 on 2026-05-26 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_medical_notes'),
        ('clinical', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMedicalRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('allergy', 'Allergy'), ('diagnosed_condition', 'Diagnosed Condition'), ('chronic_illness', 'Chronic Illness'), ('deformity', 'Deformity'), ('special_note', 'Special Medical Note')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('diagnosed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_medical_records', to='accounts.studentprofile')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='visits.visit')),
            ],
            options={
                'db_table': 'clinical_student_medical_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'record_type', 'is_active'], name='clinical_st_student_80e844_idx'), models.Index(fields=['visit', 'record_type'], name='clinical_st_visit_i_cfe1b4_idx')],
            },
        ),
    ]
