# Generated by Django 5.1.15 on 2026-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_labrequesttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequesttest',
            name='attachment',
            field=models.FileField(blank=True, upload_to='lab_tests/%Y/%m/'),
        ),
    ]
