# Generated by Django 5.1.15 on 2026-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_labrequesttest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequesttest',
            name='interpretation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labrequesttest',
            name='technician_notes',
            field=models.TextField(blank=True),
        ),
    ]
