# Generated by Django 5.1.15 on 2026-06-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='followup',
            new_name='clinical_fo_patient_82cc10_idx',
            old_name='clinical_follow_up_patient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='followup',
            new_name='clinical_fo_visit_i_8711ad_idx',
            old_name='clinical_follow_up_visit_scheduled_idx',
        ),
        migrations.AddField(
            model_name='followup',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_type',
            field=models.CharField(choices=[('medication_review', 'Medication Review'), ('lab_review', 'Lab Review'), ('injection_course', 'Injection Course'), ('consultation_review', 'Consultation Review'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
    ]
