# Generated by Django 5.1.15 on 2026-05-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_treatment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('follow_up', 'Follow-up'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('treatment', 'Treatment'), ('emergency', 'Emergency'), ('general', 'General')], max_length=24),
        ),
    ]
