# Generated by Django 5.1.15 on 2026-05-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='emergency_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='emergency.emergencyevent'),
        ),
    ]
