# Generated by Django 5.1.15 on 2026-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
    ]
