# Generated by Django 5.1.15 on 2026-05-26 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('at_nurse', 'At Nurse'), ('at_doctor', 'At Doctor'), ('awaiting_pharmacy', 'Awaiting Pharmacy'), ('awaiting_lab', 'Awaiting Lab'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=32)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], db_index=True, default='normal', max_length=16)),
                ('chief_complaint', models.TextField(blank=True)),
                ('reception_notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(db_index=True, default=False)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'visits_visit',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('assigned_nurse_queue', models.BooleanField(default=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_logs', to='visits.visit')),
            ],
            options={
                'db_table': 'visits_reception_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('reception', 'Reception'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('lab', 'Lab')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='waiting', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='visits.visit')),
            ],
            options={
                'db_table': 'visits_queue_entry',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='visits.visit')),
            ],
            options={
                'db_table': 'visits_consultation',
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intake_notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_records', to='visits.visit')),
            ],
            options={
                'db_table': 'visits_vitals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'priority'], name='visits_visi_status_262009_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['student', 'registered_at'], name='visits_visi_student_b63baf_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['stage', 'status', 'position'], name='visits_queu_stage_a980d6_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['visit', 'stage'], name='visits_queu_visit_i_1f413a_idx'),
        ),
    ]
