# Generated by Django 5.1.15 on 2026-05-26 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('dispatched', 'Dispatched'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='triggered', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('dial_triggered', models.BooleanField(default=False)),
                ('dial_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('priority_override', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to='accounts.studentprofile')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='visits.visit')),
            ],
            options={
                'db_table': 'emergency_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='emergency_e_status_963a59_idx')],
            },
        ),
    ]
